//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmgularJsTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitsOfMeasure
    {
        public UnitsOfMeasure()
        {
            this.Items = new HashSet<Item>();
        }
    
        public int id { get; set; }
        public string Symbol { get; set; }
        public string Des { get; set; }
    
        public virtual ICollection<Item> Items { get; set; }
    }
}
